exclude: 'build/'
minimum_pre_commit_version: 4.4.0
default_language_version:
    golang: '1.22' 

repos:

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
    -   id: insert-license
        files: \.go$
        args:
          - --license-filepath
          - scripts/license_header.txt
          - --comment-style
          - '//'
    -   id: insert-license
        files: \.sh$
        args:
          - --license-filepath
          - scripts/license_header.txt
          - --comment-style
          - '#'


